# Perfil Docker — Auth Service
# Las variables sensibles se inyectan desde docker-compose.yml como ENV

spring.application.name=auth-service
server.port=8081

# Eureka: apunta al contenedor 'discovery' (nombre DNS interno de Docker)
eureka.client.service-url.defaultZone=http://discovery:8761/eureka

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
