spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ============================================================
# RUTAS DEL GATEWAY
# ============================================================

# Auth Service → rutas públicas, sin filtro JWT
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Event Service → rutas protegidas con JWT
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=lb://event-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/events/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Inscription Service
spring.cloud.gateway.routes[2].id=inscrip-service
spring.cloud.gateway.routes[2].uri=lb://inscrip-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inscriptions/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# ============================================================
# CORS GLOBAL
# ============================================================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000,http://localhost:5500
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Actuator
management.endpoints.web.exposure.include=health,info,gateway

# JWT secret (debe ser igual al del auth-service)
app.jwt.secret=event-manager-super-secret-key-2024-minimum-256-bits-long
