spring.application.name=api-gateway
server.port=${PORT:8080}

# User Service
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

# Auth Service

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

# Event Service

spring.cloud.gateway.server.webmvc.routes[2].id=event-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${EVENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/events/**

# Inscrip Service (pendiente)

spring.cloud.gateway.server.webmvc.routes[3].id=inscrip-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${INSCRIP_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/inscriptions/**

# Notification Service (pendiente)

spring.cloud.gateway.server.webmvc.routes[4].id=notification-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/notifications/**

# Actuator

management.endpoints.web.exposure.include=health,info