spring.application.name=user-service
server.port=${PORT:8082}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/user_db}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true