spring.application.name=discovery-service
server.port=8761

# Deshabilitar auto-registro en sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard visual disponible en http://localhost:8761
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

management.endpoints.web.exposure.include=health,info
