# Perfil Docker — Event Service

spring.application.name=event-service
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://discovery:8761/eureka

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
